// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emqigcovjkfupxnjakss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtcWlnY292amtmdXB4bmpha3NzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTE1MTEsImV4cCI6MjA2MjM2NzUxMX0.3Kh8C02mEgRRrp52l8JKRYmViFyPDP-Lzr-40WEq-FQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);